import { 
  ArrowLeft, 
  FileText, 
  Download, 
  Printer, 
  Search, 
  Filter,
  Calendar, 
  User, 
  Phone, 
  Mail, 
  Heart, 
  Activity, 
  Pill,
  AlertCircle,
  CheckCircle,
  Clock,
  Eye,
  Edit
} from 'lucide-react'
import { useState } from 'react'
import { useStaff } from '../context/StaffContext'
import PatientReportsView from './PatientReportsView'

const DoctorReportsPage = () => {
  const { 
    appointedPatients, 
    setActiveTab, 
    selectedPatient, 
    showPatientReports,
    handlePatientSelect,
    handleReportUpdate
  } = useStaff()
  
  const [searchTerm, setSearchTerm] = useState('')
  const [filterSeverity, setFilterSeverity] = useState('all')

  if (showPatientReports && selectedPatient) {
    return <PatientReportsView />
  }

  const filteredPatients = appointedPatients.filter(patient => {
    const matchesSearch = patient.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         patient.id.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         patient.condition.toLowerCase().includes(searchTerm.toLowerCase())
    
    const matchesSeverity = filterSeverity === 'all' || 
                           patient.severity.toLowerCase() === filterSeverity.toLowerCase()
    
    return matchesSearch && matchesSeverity
  })

  const getSeverityColor = (severity) => {
    switch (severity.toLowerCase()) {
      case 'critical': return 'bg-red-100 text-red-800 border-red-200'
      case 'serious': return 'bg-orange-100 text-orange-800 border-orange-200'
      case 'moderate': return 'bg-yellow-100 text-yellow-800 border-yellow-200'
      case 'mild': return 'bg-blue-100 text-blue-800 border-blue-200'
      case 'stable': return 'bg-green-100 text-green-800 border-green-200'
      case 'normal': return 'bg-green-100 text-green-800 border-green-200'
      case 'controlled': return 'bg-green-100 text-green-800 border-green-200'
      default: return 'bg-gray-100 text-gray-800 border-gray-200'
    }
  }

  const downloadAllReports = () => {
    const reportContent = `
MEDICARE PLUS - ALL PATIENTS REPORT
===================================

Generated: ${new Date().toLocaleDateString()}
Total Patients: ${appointedPatients.length}

PATIENT SUMMARY
===============
${appointedPatients.map((patient, index) => `
${index + 1}. ${patient.name} (${patient.id})
   Age: ${patient.age} years
   Condition: ${patient.condition}
   Severity: ${patient.severity}
   Next Appointment: ${patient.nextAppointment} at ${patient.time}
   Location: ${patient.room}
   Contact: ${patient.phone}
   Last Visit: ${patient.lastVisit}
   
   Current Medications:
   ${patient.currentMedications.map(med => `   - ${med}`).join('\n')}
   
   Allergies:
   ${patient.allergies.map(allergy => `   - ${allergy}`).join('\n')}
   
   Vitals:
   - Blood Pressure: ${patient.vitals.bp}
   - Heart Rate: ${patient.vitals.hr}
   - Temperature: ${patient.vitals.temp}
   - Weight: ${patient.vitals.weight}
`).join('\n')}

This report contains summary information for all assigned patients.
For detailed medical reports, please access individual patient records.

Generated by: Dr. Sarah Johnson
Date: ${new Date().toLocaleDateString()}
    `

    const blob = new Blob([reportContent], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `All_Patients_Report_${new Date().toISOString().split('T')[0]}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  return (
    <div className="space-y-8">
      {/* Header */}
      <div className="bg-white/60 backdrop-blur-sm rounded-2xl shadow-lg border border-blue-200/50 p-6">
        <div className="flex items-center justify-between mb-6">
          <div className="flex items-center space-x-4">
            <button
              onClick={() => setActiveTab('dashboard')}
              className="p-2 hover:bg-gray-100 rounded-lg transition-colors"
            >
              <ArrowLeft className="w-5 h-5 text-gray-600" />
            </button>
            <div>
              <h2 className="text-2xl font-semibold text-gray-900">Patient Reports</h2>
              <p className="text-gray-600">View and manage all patient medical records</p>
            </div>
          </div>
          
          <div className="flex items-center space-x-3">
            <button
              onClick={downloadAllReports}
              className="flex items-center space-x-2 px-4 py-2 bg-blue-500 hover:bg-blue-600 text-white rounded-lg transition-colors shadow-lg"
            >
              <Download className="w-4 h-4" />
              <span>Download All</span>
            </button>
            <button className="flex items-center space-x-2 px-4 py-2 bg-gray-500 hover:bg-gray-600 text-white rounded-lg transition-colors shadow-lg">
              <Printer className="w-4 h-4" />
              <span>Print</span>
            </button>
          </div>
        </div>

        {/* Search and Filter */}
        <div className="flex items-center space-x-4">
          <div className="flex-1 relative">
            <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 w-5 h-5 text-gray-400" />
            <input
              type="text"
              placeholder="Search patients by name, ID, or condition..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
            />
          </div>
          
          <div className="flex items-center space-x-2">
            <Filter className="w-5 h-5 text-gray-500" />
            <select
              value={filterSeverity}
              onChange={(e) => setFilterSeverity(e.target.value)}
              className="px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
            >
              <option value="all">All Severities</option>
              <option value="critical">Critical</option>
              <option value="serious">Serious</option>
              <option value="moderate">Moderate</option>
              <option value="mild">Mild</option>
              <option value="stable">Stable</option>
              <option value="controlled">Controlled</option>
            </select>
          </div>
        </div>
      </div>

      {/* Patients List */}
      <div className="bg-white/60 backdrop-blur-sm rounded-2xl shadow-lg border border-blue-200/50 p-8">
        <div className="flex items-center justify-between mb-6">
          <h3 className="text-xl font-semibold text-gray-900 flex items-center">
            <FileText className="w-6 h-6 mr-3 text-blue-600" />
            All Patients ({filteredPatients.length})
          </h3>
        </div>

        <div className="space-y-4">
          {filteredPatients.map((patient) => (
            <div
              key={patient.id}
              className="bg-white/80 backdrop-blur-sm rounded-xl p-6 border border-[#D7CCC8]/20 hover:border-[#D7CCC8]/40 transition-all hover:shadow-lg"
            >
              <div className="flex items-center justify-between mb-4">
                <div className="flex items-center space-x-4">
                  <div className="w-12 h-12 bg-blue-100 rounded-full flex items-center justify-center">
                    <span className="text-lg font-bold text-blue-600">
                      {patient.name.split(' ').map(n => n[0]).join('')}
                    </span>
                  </div>
                  <div>
                    <h4 className="text-lg font-semibold text-gray-900">{patient.name}</h4>
                    <p className="text-sm text-gray-600">{patient.age} years • {patient.gender} • {patient.bloodGroup}</p>
                    <p className="text-sm text-gray-500">ID: {patient.id}</p>
                  </div>
                </div>
                <div className="text-right">
                  <span className={`px-3 py-1 rounded-full text-sm font-medium border ${getSeverityColor(patient.severity)}`}>
                    {patient.severity}
                  </span>
                  <p className="text-sm text-gray-600 mt-1">{patient.status}</p>
                </div>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-4">
                <div className="bg-gray-50/80 p-3 rounded-lg">
                  <p className="text-xs text-gray-600 mb-1">Condition</p>
                  <p className="font-semibold text-gray-900">{patient.condition}</p>
                </div>
                <div className="bg-gray-50/80 p-3 rounded-lg">
                  <p className="text-xs text-gray-600 mb-1">Next Appointment</p>
                  <p className="font-semibold text-gray-900">{patient.nextAppointment}</p>
                  <p className="text-sm text-gray-600">{patient.time}</p>
                </div>
                <div className="bg-gray-50/80 p-3 rounded-lg">
                  <p className="text-xs text-gray-600 mb-1">Location</p>
                  <p className="font-semibold text-gray-900">{patient.room}</p>
                </div>
              </div>

              <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-4">
                <div className="text-center">
                  <p className="text-xs text-gray-600">Blood Pressure</p>
                  <p className="font-semibold text-gray-900">{patient.vitals.bp}</p>
                </div>
                <div className="text-center">
                  <p className="text-xs text-gray-600">Heart Rate</p>
                  <p className="font-semibold text-gray-900">{patient.vitals.hr} bpm</p>
                </div>
                <div className="text-center">
                  <p className="text-xs text-gray-600">Temperature</p>
                  <p className="font-semibold text-gray-900">{patient.vitals.temp}</p>
                </div>
                <div className="text-center">
                  <p className="text-xs text-gray-600">Weight</p>
                  <p className="font-semibold text-gray-900">{patient.vitals.weight}</p>
                </div>
              </div>

              <div className="flex items-center justify-between">
                <div className="flex items-center space-x-4 text-sm text-gray-600">
                  <div className="flex items-center space-x-1">
                    <Phone className="w-4 h-4" />
                    <span>{patient.phone}</span>
                  </div>
                  <div className="flex items-center space-x-1">
                    <Clock className="w-4 h-4" />
                    <span>Last visit: {patient.lastVisit}</span>
                  </div>
                </div>
                <div className="flex items-center space-x-2">
                  <button
                    onClick={() => handlePatientSelect(patient)}
                    className="flex items-center space-x-1 px-3 py-1 bg-blue-100 hover:bg-blue-200 text-blue-700 rounded-lg transition-colors text-sm"
                  >
                    <Eye className="w-4 h-4" />
                    <span>View Reports</span>
                  </button>
                  <button
                    onClick={() => handleReportUpdate(patient)}
                    className="flex items-center space-x-1 px-3 py-1 bg-green-100 hover:bg-green-200 text-green-700 rounded-lg transition-colors text-sm"
                  >
                    <Edit className="w-4 h-4" />
                    <span>Update</span>
                  </button>
                </div>
              </div>
            </div>
          ))}
        </div>

        {filteredPatients.length === 0 && (
          <div className="text-center py-12">
            <div className="w-20 h-20 bg-gray-100 rounded-full flex items-center justify-center mx-auto mb-6">
              <FileText className="w-10 h-10 text-gray-400" />
            </div>
            <h3 className="text-lg font-semibold text-gray-900 mb-2">No patients found</h3>
            <p className="text-gray-600">
              {searchTerm || filterSeverity !== 'all' 
                ? "Try adjusting your search or filter criteria."
                : "No patients assigned yet."
              }
            </p>
          </div>
        )}
      </div>
    </div>
  )
}

export default DoctorReportsPage